# Generated by Django 2.1.2 on 2018-11-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0005_auto_20181105_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lng',
            new_name='longitude',
        ),
    ]
