# Generated by Django 2.1.2 on 2018-11-08 19:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0007_auto_20181108_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
