# Generated by Django 2.1.2 on 2018-11-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0008_auto_20181108_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geolocation',
            field=models.TextField(blank=True, max_length=2200, null=True),
        ),
    ]
